### PR TITLE
feature: add hack dockerfiles and remove unnecessary code

### LINKED ISSUE #1: go mod tidy doesn't work
Output `go mod tidy`:
```zsh
go: downloading github.com/digitalocean/godo v1.65.0
go: downloading github.com/kanisterio/kanister v0.0.0-20210903215800-f8e63bf1364d
go: downloading github.com/google/go-querystring v1.0.0
go: downloading github.com/jpillora/backoff v1.0.0
go: finding module for package k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset
github.com/viveksinghggits/kluster/pkg/client/informers/internalversion imports
	k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset: module k8s.io/kubernetes@latest found (v1.23.4), but does not contain package k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset
```
Output `go version`:
```
go version go1.17.7 linux/amd64
```
Output `uname -a`:
```
Linux alias-rahil 5.15.25-1-lts #1 SMP Wed, 23 Feb 2022 12:02:12 +0000 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by alias-rahil**
1. Remove unnecessary code
2. New CI pipeline to update generated code and crds if required

closes #1

### CODE REVIEW

**Comment by viveksinghggits** [comment]
Hi @alias-rahil 
can you please summarise what exactly are we trying to achieve in this PR. If this is to just close the #1 , I would rather prefer to merge the change directly. instead of running these things in CI.

**Comment by alias-rahil** [comment]
Hey so the the CI is to make sure the crds and the generated code are always up to date. If you decided to add another field to the `Kluster` struct but forgot to regenerate the crds and deepcopy interfaces, the CI will add it for you. It's not required, lmk if you want me to remove the ci file.

I would still insist on retaining the `hack` directory though, a lot of other repos maintain bash scripts for the same purpose but I couldn't get it to work for me so instead I went with having dockerfiles.

**Comment by viveksinghggits** [comment]
Hi @alias-rahil 
I am a bit hesitant about merging this with the entire change. I personally don't think that letting CI generate the code for the fields that someone added is a good idea. If someone is adding the field they would run code generator to make sure things are working as expected.
I agree, about the hack directory we should have hack directory that can be run locally as well to generate the code.

**Comment by viveksinghggits** [comment]
Also, let's make sure to add steps in `README` on how to use that.

**Comment by alias-rahil** [comment]
@viveksinghggits 
I removed the CI as requested and added docs for using the hack dockerfiles. Can you review the changes?

**Comment by viveksinghggits** [comment]
Hi Rahil,
Thanks for your PR I appreciate it. Even though I was not able to decide initially but now I think we should not merge this PR. And the reason is, people are going to come here after watching the videos and would see some of the code that was not covered in those videos.
I apologise, I should have shared this very initially itself.

**Comment by alias-rahil** [comment]
We can close this now I think.

**Pull request closed without merging**
